[project]
name = "curso-pln-2026-1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jupyter-ruff>=0.3.0",
    "jupyterlab>=4.4.6",
    "jupyterlab-rise>=0.43.1",
    "jupyterlab-vim>=4.1.4",
]
